global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'trade-copier-web'
    static_configs:
      - targets: ['web:3000']

  - job_name: 'trade-copier-websocket'
    static_configs:
      - targets: ['websocket:3001']

